### ISSUE TITLE
[Addition] I made a shader support

### ISSUE THREAD

**Issue by Toilet-Lord** [firenh/rustediron#1]
I always make shader support for mods I like the most! The files only need to be added to the folder where the textures are, that's it! The shader will take care of the rest!
**((Works best with Seus Ptgi))**

![Rusted Iron Shader](https://user-images.githubusercontent.com/76745705/147718464-89856273-e4b3-41d8-9bcd-a33ec30779cf.gif)

Here are the files and the name they should have for it to work **(important)**:

Exposed:
![exposed_iron_s](https://user-images.githubusercontent.com/76745705/147717396-f380cad6-bb4a-4550-8f7c-17365335b951.png) "exposed_iron_s"
 ![exposed_iron_n](https://user-images.githubusercontent.com/76745705/147718424-9d5ac156-3288-428a-9985-35db6dc6c8cb.png) "exposed_iron_n"

Weathered:
![weathered_iron_s](https://user-images.githubusercontent.com/76745705/147717412-61a6b49a-2151-495e-a1c7-081df2589e30.png) "weathered_iron_s"
![weathered_iron_n](https://user-images.githubusercontent.com/76745705/147718440-653141c8-a09f-48a3-8d40-79ecba4b9a3b.png) "weathered_iron_n"

Rusted:
![rusted_iron_s](https://user-images.githubusercontent.com/76745705/147717416-e81b5f81-b406-4dee-a54e-3751fff0f35f.png) "rusted_iron_s"
![rusted_iron_n](https://user-images.githubusercontent.com/76745705/147718452-80c988ea-0742-48d6-b282-47087cb4cbb8.png) "rusted_iron_n"

**Comment by firenh** [comment]
okay this is genuinely so cool, thank you so much! is it okay if i add this to the base mod? if so, how do you want to be credited?

**Comment by firenh** [comment]
i went ahead and added the changed to a different branch in the repo (changes haven't been added yet), did i add it right? i tried testing it with the shaders you said you used but my minecraft client just crashed lol 

of course if you'd rather me not add it to the base mod i can delete the files, it's up to you

https://github.com/firenh/rustediron/tree/shader-support-from-toilet-man

**Comment by Toilet-Lord** [comment]
> okay this is genuinely so cool, thank you so much! is it okay if i add this to the base mod? if so, how do you want to be credited?

You're welcome, thank you for making this mod! You do what you want but a little shoutout on modrinth/curseforge/GitHub (like you did) would warm my heart!

As for the files and the base mod:
Everything is done perfectly, they're at the right place
And I was hoping you'd add them to the base mod. It's a big "YES!" from me.

**Comment by firenh** [comment]
okay thank you! i'm gonna merge the branches right now. i'll put the readme on Modrinth as well with the next update. i haven't yet submitted the mod to curseforge but when i do it'll have the same readme. thank you for your contribution!

**Comment by Toilet-Lord** [comment]
You're welcome! Thanks for crediting me and adding this to your mod
